variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: Full_Build
        pool:
          vmImage: windows-latest
        steps:
        - template: templates/build.yaml
  - stage: Test
    jobs:
      - job:
        strategy:
          matrix:
            Ubuntu:
              vmImage: ubuntu-18.04
            macOS:
              vmImage: macOS-10.15
            Windows_PS7:
              vmImage: windows-latest
        pool:
          vmImage: $[variables['vmImage']]
        steps:
        - template: templates/test.yaml
      - job:
        strategy:
          matrix:
            Windows_WinPS:
              vmImage: windows-latest
              useWinPS: true
        pool:
          vmImage: $[ variables['vmImage'] ]
        steps:
        - template: templates/tests.yaml
          parameters:
            useWinPS: true
