steps: 

- pwsh: |
    ./tools/ensureInvokeBuildInstalled.ps1
    Invoke-Build Build
  displayName: Build Module

- publish: '$(Build.SourcesDirectory)/out'
  artifact: unsigned
  displayName: Publish unsigned artifacts
