steps:

- pwsh: |
    if ("$(System.ArtifactsDirectory)" -ne "$(Build.ArtifactsStagingDirectory)")
    {
        Copy-Item -Recurse -Force -LiteralPath "$(System.ArtifactsDirectory)" -Destination "$(Build.ArtifactsStagingDirectory)"
    }
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    New-Catalog -Path "$(Build.ArtifactsStagingDirectory)/out" -OutputPath "$(Build.ArtifactsStagingDirectory)/catalog/PSArm.cat"
  displayName: 'Create file catalog'

- task: PkgESCodeSign@10
  displayName: 'Sign file catalog'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: PSArm.cat
    inPathRoot: '$(Build.ArtifactsStagingDirectory)\catalog'
    outPathRoot: '$(Build.ArtifactsStagingDirectory)\out\PSArm'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(Build.ArtifactsStagingDirectory)\out'