steps:

- pwsh: |
    if ("$(System.ArtifactsDirectory)" -ne "$(Build.ArtifactStagingDirectory)")
    {
        Copy-Item -Recurse -Force -LiteralPath "$(System.ArtifactsDirectory)" -Destination "$(Build.ArtifactStagingDirectory)"
    }
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    New-Catalog -Path "$(Build.ArtifactStagingDirectory)/out" -OutputPath "$(Build.ArtifactStagingDirectory)/catalog/PSArm.cat"
  displayName: 'Create file catalog'

- task: PkgESCodeSign@10
  displayName: 'Sign file catalog'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: PSArm.cat
    inPathRoot: '$(Build.ArtifactStagingDirectory)\catalog'
    outPathRoot: '$(Build.ArtifactStagingDirectory)\out\PSArm'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(Build.ArtifactStagingDirectory)\out'