steps:

- pwsh: |
    tree "$(System.ArtifactsDirectory)"
  displayName: Show artifacts directory

- pwsh: |
    $signedPath = "$(Build.ArtifactStagingDirectory)\signed"
    if (-not (Test-Path $signedPath))
    {
        New-Item $signedPath -ItemType Directory -Verbose
    }
  displayName: Ensure signed directory exists

- task: PkgESCodeSign@10
  displayName: Sign Assemblies
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: '$(Build.SourcesDirectory)\tools\release\codeSigning.xml'
    inPathRoot: '$(System.ArtifactsDirectory)\out'
    outPathRoot: '$(Build.ArtifactStagingDirectory)\signed'

- pwsh: |
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    Copy-SignedFiles -SignedDirPath "$(Build.ArtifactStagingDirectory)/signed" -Destination "$(Build.ArtifactStagingDirectory)/out"
  displayName: 'Copy signed files into place'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(Build.ArtifactStagingDirectory)\out'
