steps:

- checkout: ComplianceRepo
  displayName: 'Checkout the ComplianceRepo'

- checkout: self

- download: current
  artifact: unsigned
  displayName: 'Download Build Artifacts: unsigned'

- template: logArtifacts.yaml

- template: EsrpSign.yml@ComplianceRepo
  parameters:
    buildOutputPath: '$(Pipeline.Workspace)/unsigned'
    signOutputPath: '$(Pipeline.Workspace)/FirstPartySigned'
    alwaysCopy: true
    certificateId: 'CP-230012' # Authenticode certificate
    useMinimatch: true # Enable globbing
    pattern: |
      PSArm/PSArm.dll
      PSArm/*.{ps1,psm1,psd1,ps1xml}

- template: EsrpSign.yml@ComplianceRepo
  parameters:
    buildOutputPath: '$(Pipeline.Workspace)/FirstPartySigned'
    signOutputPath: '$(Pipeline.Workspace)/signed'
    alwaysCopy: true
    certificateId: 'CP-231522' # Third-party certificate
    useMinimatch: true # This enables the use of globbing
    pattern: |
      PSArm/Newtonsoft.Json.dll

- pwsh: |
    Import-Module '$(Build.SourcesDirectory)/PSArm/tools/release/ReleaseTools.psm1'
    Assert-FilesAreSigned -Path '$(System.ArtifactsDirectory)/signed/PSArm'
  displayName: Validate that files are signed

- publish: '$(Pipeline.Workspace)/signed'
  artifact: signed
  displayName: Publish signed artifacts
