steps:

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'
  inputs:
    snapshotForceEnabled: true
    failOnAlert: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-antimalware.AntiMalware@3
  displayName: 'Run Defender Scan'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    toolMajorVersion: V2
    debugMode: false
  continueOnError: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-binskim.BinSkim@3
  displayName: 'Run BinSkim'
  inputs:
    InputType: Basic
    AnalyzeTarget: '$(System.ArtifactsDirectory)\out\PSArm\*.dll'
    AnalyzeSymPath: 'SRV*'
    AnalyzeVerbose: true
    AnalyzeHashes: true
    AnalyzeStatistics: true
  continueOnError: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
  displayName: 'Run PoliCheck'
  inputs:
    targetType: F
    optionsFC: 0
    optionsXS: 0
    optionsPE: '1|2|3|4'
    optionsHMENABLE: 0
    toolVersion: 5.8.2.1
  continueOnError: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
  displayName: 'Publish Security Analysis Logs to Build Artifacts'
  continueOnError: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-uploadtotsa.TSAUpload@1
  displayName: 'TSA upload to Codebase: PSSecretsManagement_202001 Stamp: Azure'
  inputs:
    codeBaseName: PSSecretsManagement_202001
    tsaVersion: TsaV2
    uploadFortifySCA: false
    uploadFxCop: false
    uploadModernCop: false
    uploadPREfast: false
    uploadRoslyn: false
    uploadTSLint: false
    uploadAPIScan: false

- task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
  displayName: 'Create Security Analysis Report'
  inputs:
    TsvFile: false
    APIScan: false
    BinSkim: false
    CredScan: true
    PoliCheck: true
    PoliCheckBreakOn: Severity2Above
