steps:

# See https://docs.microsoft.com/en-us/azure/security/develop/yaml-configuration for configuration of these tasks

- checkout: ComplianceRepo
  displayName: 'Checkout the ComplianceRepo'

- checkout: self

- download: signed
  displayName: 'Download Build Artifacts: signed'

- template: logArtifacts.yaml

- template: assembly-module-compliance.yml@ComplianceRepo
  parameters:
    # binskim
    AnalyzeTarget: '$(Build.ArtifactStagingDirectory)/signed/PSArm/*.dll'
    AnalyzeSymPath: 'SRV*'
    # Component governance
    sourceScanPath: '$(Build.SourcesDirectory)/PSArm'
    # CredScan
    suppressionsFile: ''
    # TermCheck AKA PoliCheck
    targetArgument: '$(Build.SourcesDirectory)/PSArm'
    optionsUEPATH: '$(Build.SourcesDirectory)/PSArm/tools/release/UserExclusions.xml'
    optionsRulesDBPath: ''
    optionsFTPath: '$(Build.SourcesDirectory)/PSArm/tools/release/FileTypeSet.xml'
    # TSA upload
    codeBaseName: PSArm_202009
    # Turn off ApiScan
    APIScan: false
