parameters:

# Location of PSArm module
- name: psArmPath
  type: string
# If true, uses Windows PowerShell 5.1, otherwise uses PowerShell 7
- name: useWinPS
  type: boolean
  default: false

steps:

- task: PowerShell@2
  displayName: 'Pester Tests'
  inputs:
    targetType: inline
    pwsh: ${{ not(parameters.useWinPS) }}
    script: |
      ./tools/ensureInvokeBuildInstalled.ps1
      Invoke-Build TestPester -RunTestsInProcess -RunTestsInCIMode -TestPSArmPath '${{ parameters.psArmPath }}'

- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: 'testResults.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
