steps:

- template: download.yaml
  parameters:
    artifact: signed

- pwsh: |
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    Publish-Module -ModulePath "$(Build.ArtifactStagingDirectory)/signed/PSArm"
  displayName: 'Publish to PSGallery'
