steps:

- task: PkgESCodeSign@10
  displayName: Sign Assemblies
  inputs:
    signConfigXml: tools/release/signing.xml
    inPathRoot: '$(System.ArtifactsDirectory)\out'
    outPathRoot: '$(System.ArtifactsDirectory)\signed'

- pwsh:
  filePath: tools/release/copySignedFiles
  arguments: >
    -SignedDirPath "$(System.ArtifactsDirectory)\signed"
    -Destination "$(System.ArtifactsDirectory)\out"
  displayName: 'Copy signed files into place'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(System.ArtifactsDirectory)\out'