steps:

- task: PkgESCodeSign@10
  displayName: Sign Assemblies
  inputs:
    signConfigXml: tools/release/codeSigning.xml
    inPathRoot: '$(System.ArtifactsDirectory)\out'
    outPathRoot: '$(System.ArtifactsDirectory)\signed'

- task: PowerShell@2
  displayName: 'Copy signed files into place'
  inputs:
    pwsh: true
    filePath: tools/release/copySignedFiles
    arguments: >
      -SignedDirPath "$(System.ArtifactsDirectory)\signed"
      -Destination "$(System.ArtifactsDirectory)\out"

- task: PowerShell@2
  condition: succeededOrFailed()
  displayName: 'Create file catalog'
  inputs:
    pwsh: true
    filePath: tools/release/newCatalog.ps1
    arguments: >
      -Path "$(System.ArtifactsDirectory)\out"
      -OutputPath "$(System.ArtifactsDirectory)\catalog\PSArm.cat"

- task: PkgESCodeSign@10
  displayName: 'Sign file catalog'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: PSArm.cat
    inPathRoot: '$(System.ArtifactsDirectory)\catalog'
    outPathRoot: '$(System.ArtifactsDirectory)\out'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(System.ArtifactsDirectory)\out'