steps:

- task: PkgESCodeSign@10
  displayName: Sign Assemblies
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: '$(Build.SourcesDirectory)\tools\release\codeSigning.xml'
    inPathRoot: '$(System.ArtifactsDirectory)\out'
    outPathRoot: '$(System.ArtifactsDirectory)\signed'

- pwsh: |
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    Copy-SignedFiles -SignedDirPath "$(System.ArtifactsDirectory)\signed" -Destination "$(System.ArtifactsDirectory)\out"
  displayName: 'Copy signed files into place'

- pwsh: |
    Import-Module "$(Build.SourcesDirectory)/tools/release/ReleaseTools.psm1"
    New-Catalog -Path "$(System.ArtifactsDirectory)\out" -OutputPath "$(System.ArtifactsDirectory)\catalog\PSArm.cat"
  condition: succeededOrFailed()
  displayName: 'Create file catalog'

- task: PkgESCodeSign@10
  displayName: 'Sign file catalog'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    signConfigXml: PSArm.cat
    inPathRoot: '$(System.ArtifactsDirectory)\catalog'
    outPathRoot: '$(System.ArtifactsDirectory)\out\PSArm'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSArm'
  inputs:
    artifactName: signed
    pathToPublish: '$(System.ArtifactsDirectory)\out'