parameters:
- name: useWinPS
  type: boolean
  default: false

steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts: unsigned'
    inputs:
      artifactName: unsigned
  - template: pester.yaml
    parameters:
      useWinPS: ${{ parameters.useWinPS }}
      psArmPath: '$(System.ArtifactsDirectory)/unsigned/PSArm'
