variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:

  - template: templates/buildAndTest.yaml

# TODO: Work out when we need to run this and how
#  - stage: Compliance
#    jobs:
#      - job: Compliance
#        steps:
#        - template: templates/steps/ciCompliance.yaml