variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:

  - template: templates/buildAndTest.yaml

  - stage: Compliance
    dependsOn: Build
    jobs:
      - job: Compliance
        pool: 'Package ES CodeHub Lab E'
        steps:
          - template: templates/steps/download.yaml
          - template: templates/steps/compliance.yaml

  - stage: Signing
    dependsOn: Compliance
    jobs:
      - job: CodeSigning
        displayName: Code Signing
        pool: 'Package ES CodeHub Lab E'
        steps:
          - template: templates/steps/download.yaml
          - template: templates/steps/codeSigning.yaml
      - job: CatalogSigning
        dependsOn: CodeSigning
        displayName: Catalog Signing
        pool: 'Package ES CodeHub Lab E'
        steps:
          - template: templates/steps/download.yaml
          - template: templates/steps/catalogSigning.yaml

  - stage: Publish
    dependsOn:
      - Tests
      - Signing
    jobs:
      - job: PublishToGallery
        displayName: Publish to PSGallery
        steps:
          - template: templates/steps/download.yaml
          - template: templates/steps/publishToGallery.yaml
      - job: PublishToGitHub
        displayName: Publish GitHub release
        steps:
          - template: templates/steps/download.yaml
          - template: templates/steps/publishToGitHub.yaml
