variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:

  - template: templates/buildAndTest.yaml

  - stage: Compliance
    dependsOn: Build
    jobs:
      - job:
        pool:
          vmImage: windows-latest
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts: out Folder'
            inputs:
              artifactName: out
          - template: templates/steps/compliance.yaml